-- if true then return {} end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE

-- AstroUI provides the basis for configuring the AstroNvim User Interface
-- Configuration documentation can be found with `:h astroui`
-- NOTE: We highly recommend setting up the Lua Language Server (`:LspInstall lua_ls`)
--       as this provides autocomplete and documentation while editing

---@type LazySpec
return {
  {
    "AstroNvim/astroui",
    ---@type AstroUIOpts
    opts = {
      colorscheme = "everforest",
      -- AstroUI allows you to easily modify highlight groups easily for any and all colorschemes
      highlights = {
        init = {},
      },
      status = {
        use_theme_colors = true,
      },
      icons = {
        ActiveLSP = "",
        ActiveTS = " ",
        BufferClose = "",
        DapBreakpoint = "",
        DapBreakpointCondition = "",
        DapBreakpointRejected = "",
        DapLogPoint = "",
        DapStopped = "",
        DefaultFile = "",
        Diagnostic = "",
        DiagnosticError = "",
        DiagnosticHint = "",
        DiagnosticInfo = "",
        DiagnosticWarn = "",
        Ellipsis = "",
        FileModified = "",
        FileReadOnly = "",
        FoldClosed = "",
        FoldOpened = "",
        FolderClosed = "",
        FolderEmpty = "",
        FolderOpen = "",
        Git = "",
        GitAdd = "",
        GitBranch = "",
        GitChange = "",
        GitConflict = "",
        GitDelete = "",
        GitIgnored = "",
        GitRenamed = "",
        GitStaged = "",
        GitUnstaged = "",
        GitUntracked = "",
        LSPLoaded = "",
        LSPLoading1 = "",
        LSPLoading2 = "",
        LSPLoading3 = "",
        MacroRecording = "",
        Paste = "",
        Search = "",
        Selected = "",
        TabClose = "",
      },
    },
  },
  {
    "nvim-mini/mini.icons",
    optional = true,
    opts = {
      lsp = {
        array = { glyph = "" },
        boolean = { glyph = "" },
        key = { glyph = "" },
        namespace = { glyph = "" },
        null = { glyph = "" },
        number = { glyph = "" },
        object = { glyph = "" },
        package = { glyph = "" },
        string = { glyph = "" },
        class = { glyph = "" },
        color = { glyph = "" },
        constant = { glyph = "" },
        constructor = { glyph = "" },
        enum = { glyph = "" },
        enummember = { glyph = "" },
        event = { glyph = "" },
        field = { glyph = "" },
        file = { glyph = "" },
        folder = { glyph = "" },
        ["function"] = { glyph = "" },
        interface = { glyph = "" },
        keyword = { glyph = "" },
        method = { glyph = "" },
        module = { glyph = "" },
        operator = { glyph = "" },
        property = { glyph = "" },
        reference = { glyph = "" },
        snippet = { glyph = "" },
        struct = { glyph = "" },
        text = { glyph = "" },
        typeparameter = { glyph = "" },
        unit = { glyph = "" },
        value = { glyph = "" },
        variable = { glyph = "" },
      },
    },
  },
}
